import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import type { ConventionKey } from '../../shared/types'

function conventionsPath(projectPath: string): string {
  return join(projectPath, '.sneebly-interface', 'conventions.md')
}

function startTag(key: ConventionKey): string {
  return `<!-- sneebly:convention:${key}:start -->`
}

function endTag(key: ConventionKey): string {
  return `<!-- sneebly:convention:${key}:end -->`
}

export function readConventionsMd(projectPath: string): string {
  const path = conventionsPath(projectPath)
  if (!existsSync(path)) return ''
  try {
    return readFileSync(path, 'utf-8').trim()
  } catch {
    return ''
  }
}

export function upsertConvention(
  projectPath: string,
  key: ConventionKey,
  title: string,
  value: string
): void {
  const dir = join(projectPath, '.sneebly-interface')
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })

  const path = conventionsPath(projectPath)
  const current = existsSync(path) ? readFileSync(path, 'utf-8') : ''

  const block = `${startTag(key)}\n### ${title}\n\n${value.trim()}\n${endTag(key)}`

  const start = startTag(key)
  const end = endTag(key)
  const startIdx = current.indexOf(start)
  const endIdx = current.indexOf(end)

  let updated: string
  if (startIdx !== -1 && endIdx !== -1) {
    // Replace existing block
    updated =
      current.slice(0, startIdx) +
      block +
      current.slice(endIdx + end.length)
  } else {
    // Append new block
    const header = current.trim()
      ? current
      : '# Project Conventions\n\nAuto-generated by Sneebly from observed project patterns.\n'
    updated = header.trimEnd() + '\n\n' + block + '\n'
  }

  writeFileSync(path, updated, 'utf-8')
}

export function removeConvention(projectPath: string, key: ConventionKey): void {
  const path = conventionsPath(projectPath)
  if (!existsSync(path)) return

  const content = readFileSync(path, 'utf-8')
  const start = startTag(key)
  const end = endTag(key)

  const startIdx = content.indexOf(start)
  const endIdx = content.indexOf(end)
  if (startIdx === -1 || endIdx === -1) return

  const before = content.slice(0, startIdx).replace(/\n+$/, '')
  const after = content.slice(endIdx + end.length).replace(/^\n+/, '\n')
  writeFileSync(path, before + after, 'utf-8')
}
